### ISSUE TITLE
not required

### ISSUE THREAD

**Issue by awaazde** [Ajinkya009/ProjectManagement#1]
This is not great design. You are combining data from two different APIs in an awkward way. If you want users you sh get it from User API.

If you are manually serializing anything in your ViewSet chances are you are doing something wrong.

https://github.com/Ajinkya009/ProjectManagement/blob/16428be0df942dbfb6ff38dd7c354dc0927ff983/taskManager/views.py#L35

**Comment by Ajinkya009** [comment]
I've created two separate apis and removed this method.
