### ISSUE TITLE
What's component vs. module? How could your app benefit organizationally by not having every component stuffed into single module?

### ISSUE THREAD

**Issue by awaazde** [Ajinkya009/ProjectManagement#11]
https://github.com/Ajinkya009/ProjectManagement/blob/16428be0df942dbfb6ff38dd7c354dc0927ff983/client/taskManager/src/app/app.module.ts#L37

**Comment by Ajinkya009** [comment]
I've created separate modules for account,dashboard,project & task. Each module will contain respective services as well.
